// Test generated by RoostGPT for test Csharp-dev-toys using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using NUnit.Framework;
using DevToys.Api.Tools;

namespace DevToys.Api.Tools
{
    [TestFixture]
    public class CompactOverlaySizeAttributeTest
    {
        [Test]
        public void TestCompactOverlaySizeAttribute_CompactOverlaySizeAttribute_4a612ddc92()
        {
            // Arrange
            int expectedHeight = 100;
            int expectedWidth = 200;

            // Act
            CompactOverlaySizeAttribute attribute = new CompactOverlaySizeAttribute(expectedHeight, expectedWidth);

            // Assert
            Assert.AreEqual(expectedHeight, attribute.CompactOverlayHeight);
            Assert.AreEqual(expectedWidth, attribute.CompactOverlayWidth);
        }

        [Test]
        public void TestCompactOverlaySizeAttribute_CompactOverlaySizeAttribute_4a612ddc93()
        {
            // Arrange
            int expectedHeight = 0;
            int expectedWidth = 0;

            // Act
            CompactOverlaySizeAttribute attribute = new CompactOverlaySizeAttribute(expectedHeight, expectedWidth);

            // Assert
            Assert.AreEqual(expectedHeight, attribute.CompactOverlayHeight);
            Assert.AreEqual(expectedWidth, attribute.CompactOverlayWidth);
        }
    }
}
