// Test generated by RoostGPT for test Csharp-dev-toys using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using NUnit.Framework;
using DevToys.Api.Tools;

namespace DevToys.Api.Tools.Test
{
    [TestFixture]
    public class TestToolProviderViewItem_AddChildTool_adc5d24579
    {
        [Test]
        public void Test_AddChildTool_Success()
        {
            // Arrange
            ToolProviderViewItem parent = new ToolProviderViewItem();
            ToolProviderViewItem child = new ToolProviderViewItem();

            // Act
            parent.AddChildTool(child);

            // Assert
            Assert.AreEqual(1, parent.ChildrenTools.Count);
            Assert.IsTrue(parent.MenuItemShouldBeExpanded);
            Assert.IsTrue(child.PropertyChanged != null);
        }

        [Test]
        public void Test_AddChildTool_NullChild()
        {
            // Arrange
            ToolProviderViewItem parent = new ToolProviderViewItem();

            // Act and Assert
            Assert.Throws<ArgumentNullException>(() => parent.AddChildTool(null));
        }
    }
}
