// Test generated by RoostGPT for test Csharp-dev-toys using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using System;
using System.Threading;
using System.Threading.Tasks;
using DevToys.Api.Core;
using DevToys.Models;
using Newtonsoft.Json;
using NUnit.Framework;

namespace DevToys.Core.Test.MarketingService
{
    [TestFixture]
    public class TestMarketingService
    {
        [Test]
        public void TestMarketingService_MarketingService_a25095968a()
        {
            //TODO: Change the value of notificationService to a valid INotificationService object
            INotificationService notificationService = null;

            var marketingService = new MarketingService(notificationService);

            //TODO: Add assertion to verify that the _notificationService field is set correctly
            Assert.IsNotNull(marketingService._notificationService);

            //TODO: Add assertion to verify that the _marketingState field is set correctly
            Assert.IsNotNull(marketingService._marketingState);
        }

        [Test]
        public void TestMarketingService_MarketingService_NullNotificationService()
        {
            //TODO: Change the value of notificationService to null
            INotificationService notificationService = null;

            Assert.Throws<ArgumentNullException>(() => new MarketingService(notificationService));
        }
    }
}
