// Test generated by RoostGPT for test Csharp-dev-toys using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using NUnit.Framework;
using DevToys.Api.Tools;
using System;

namespace DevToys.Api.Tools.Test
{
    [TestFixture]
    public class TestToolProviderViewItem
    {
        [Test]
        public void TestToolProviderViewItem_ToolProviderViewItem_e423826801()
        {
            // Arrange
            ToolProviderMetadata toolProviderMetadata = new ToolProviderMetadata();
            IToolProvider toolProvider = new ToolProvider();
            bool isFavorite = true;

            // Act
            ToolProviderViewItem toolProviderViewItem = new ToolProviderViewItem(toolProviderMetadata, toolProvider, isFavorite);

            // Assert
            Assert.IsNotNull(toolProviderViewItem);
            Assert.AreEqual(toolProviderMetadata, toolProviderViewItem.Metadata);
            Assert.AreEqual(toolProvider, toolProviderViewItem.ToolProvider);
            Assert.AreEqual(Array.Empty<MatchSpan>(), toolProviderViewItem.MatchedSpans);
            Assert.AreEqual(isFavorite, toolProviderViewItem.IsFavorite);
            Assert.AreEqual(toolProvider.MenuDisplayName, toolProviderViewItem.MenuDisplayName);
        }

        [Test]
        public void TestToolProviderViewItem_ToolProviderViewItem_e423826802()
        {
            // Arrange
            ToolProviderMetadata toolProviderMetadata = null;
            IToolProvider toolProvider = null;
            bool isFavorite = false;

            // Act and Assert
            Assert.Throws<System.ArgumentNullException>(() => new ToolProviderViewItem(toolProviderMetadata, toolProvider, isFavorite));
        }
    }
}
