// Test generated by RoostGPT for test Csharp-dev-toys using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using NUnit.Framework;
using DevToys.Api.Tools;

namespace DevToys.Api.Tools.Tests
{
    [TestFixture]
    public class ToolProviderViewItemTests
    {
        [Test]
        public void TestToolProviderViewItem_CreateToolProviderViewItemWithLongMenuDisplayName_95f315a138()
        {
            // Arrange
            var item = new ToolProviderViewItem(new ToolProviderMetadata(), new ToolProvider(), true);
            item.ToolProvider.SearchDisplayName = "Search Display Name";
            item.ToolProvider.MenuDisplayName = "Menu Display Name";

            // Act
            var result = ToolProviderViewItem.CreateToolProviderViewItemWithLongMenuDisplayName(item);

            // Assert
            Assert.IsNotNull(result);
            Assert.AreEqual(item.Metadata, result.Metadata);
            Assert.AreEqual(item.ToolProvider, result.ToolProvider);
            Assert.AreEqual(item.IsFavorite, result.IsFavorite);
            Assert.AreEqual(item.ToolProvider.SearchDisplayName, result.ToolProvider.SearchDisplayName);
            Assert.AreEqual(item.ToolProvider.SearchDisplayName, result.MenuDisplayName);
        }

        [Test]
        public void TestToolProviderViewItem_CreateToolProviderViewItemWithLongMenuDisplayName_NullInput_ThrowsArgumentNullException()
        {
            // Arrange
            ToolProviderViewItem item = null;

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => ToolProviderViewItem.CreateToolProviderViewItemWithLongMenuDisplayName(item));
        }
    }
}
