// Test generated by RoostGPT for test Csharp-dev-toys using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using NUnit.Framework;
using DevToys;

namespace DevToys
{
    [TestFixture]
    public class TestApp
    {
        [Test]
        public void TestApp_OnSuspending_4d027d07de()
        {
            // Test case 1
            var eventArgs = new SuspendingEventArgs();
            var app = new App();
            app.OnSuspending(null, eventArgs);
            Assert.IsTrue(eventArgs.SuspendingOperation.GetDeferral().IsCompleted);

            // Test case 2
            eventArgs = new SuspendingEventArgs();
            app = new App();
            Assert.Throws<Exception>(() => app.OnSuspending(null, eventArgs));
        }
    }
}
