// Test generated by RoostGPT for test Csharp-dev-toys using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using NUnit.Framework;
using System;
using System.Composition;
using DevToys.Api.Tools;

namespace DevToys.Api.Tools
{
    [TestFixture]
    public class NameAttributeTest
    {
        [Test]
        public void TestNameAttribute_NameAttribute_962f2eabb0()
        {
            // Test case 1
            NameAttribute nameAttribute1 = new NameAttribute("John");
            Assert.AreEqual("John", nameAttribute1.Name);

            // Test case 2
            NameAttribute nameAttribute2 = new NameAttribute(null);
            Assert.IsNull(nameAttribute2.Name);
        }
    }
}
