// Test generated by RoostGPT for test Csharp-dev-toys using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using NUnit.Framework;
using System.ComponentModel;
using DevToys.Shared.Core;
using DevToys.Shared.Api.Core;

namespace DevToys.Api.Core.Navigation
{
    [TestFixture]
    public class NavigationParameterTests
    {
        [Test]
        public void TestNavigationParameter_NavigationParameter_207970b563()
        {
            // Arrange
            IMefProvider exportProvider = new MefProvider();
            INotifyPropertyChanged viewModel = new TestViewModel();
            string clipBoardContent = "test clipboard content";
            string query = "test query";

            // Act
            var navigationParameter = new NavigationParameter(
                exportProvider,
                viewModel,
                clipBoardContent,
                query);

            // Assert
            Assert.IsNotNull(navigationParameter);
            Assert.AreEqual(exportProvider, navigationParameter.ExportProvider);
            Assert.AreEqual(viewModel, navigationParameter.ViewModel);
            Assert.AreEqual(clipBoardContent, navigationParameter.ClipBoardContent);
            Assert.AreEqual(query, navigationParameter.Query);
        }

        [Test]
        public void TestNavigationParameter_NavigationParameter_NullExportProvider()
        {
            // Arrange
            IMefProvider exportProvider = null;
            INotifyPropertyChanged viewModel = new TestViewModel();
            string clipBoardContent = "test clipboard content";
            string query = "test query";

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => new NavigationParameter(
                exportProvider,
                viewModel,
                clipBoardContent,
                query));
        }

        private class TestViewModel : INotifyPropertyChanged
        {
            public event PropertyChangedEventHandler PropertyChanged;
        }
    }
}
