// Test generated by RoostGPT for test Csharp-dev-toys using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using NUnit.Framework;

namespace DevToys.Api.Tools
{
    [TestFixture]
    public class ParentAttributeTest
    {
        [Test]
        public void TestParentAttribute_ParentAttribute_d5a0c091ed()
        {
            // Arrange
            string name = "John";
            string expectedParent = "John";

            // Act
            ParentAttribute parentAttribute = new ParentAttribute(name);

            // Assert
            Assert.AreEqual(expectedParent, parentAttribute.Parent);
        }

        [Test]
        public void TestParentAttribute_NullParentAttribute_2e9c5b9d0f()
        {
            // Arrange
            string name = null;
            string expectedParent = string.Empty;

            // Act
            ParentAttribute parentAttribute = new ParentAttribute(name);

            // Assert
            Assert.AreEqual(expectedParent, parentAttribute.Parent);
        }
    }
}
