// Test generated by RoostGPT for test Csharp-dev-toys using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using System;
using System.Composition;
using NUnit.Framework;

namespace DevToys.Api.Tools
{
    [TestFixture]
    public class MenuPlacementAttributeTests
    {
        [Test]
        public void TestMenuPlacementAttribute_MenuPlacementAttribute_ecf8abba92()
        {
            // Arrange
            MenuPlacementAttribute menuPlacementAttribute;

            // Act
            menuPlacementAttribute = new MenuPlacementAttribute(MenuPlacement.TopLeft);

            // Assert
            Assert.AreEqual(MenuPlacement.TopLeft, menuPlacementAttribute.MenuPlacement);
        }

        [Test]
        public void TestMenuPlacementAttribute_MenuPlacementAttribute_8a4b3c2d1f()
        {
            // Arrange
            MenuPlacementAttribute menuPlacementAttribute;

            // Act
            menuPlacementAttribute = new MenuPlacementAttribute(MenuPlacement.BottomRight);

            // Assert
            Assert.AreEqual(MenuPlacement.BottomRight, menuPlacementAttribute.MenuPlacement);
        }
    }
}
