// Test generated by RoostGPT for test Csharp-dev-toys using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using DevToys.Core.OOP;
using NUnit.Framework;

namespace DevToys.Core.OOP.Tests
{
    [TestFixture]
    public class AppServiceTests
    {
        [Test]
        public void TestAppService_OnAppSuspending_ShouldCompleteDeferral()
        {
            // Arrange 
            var appService = new AppService();
            var suspendingEventArgs = new SuspendingEventArgs();

            // Act 
            appService.OnAppSuspending(this, suspendingEventArgs);

            // Assert
            Assert.IsTrue(suspendingEventArgs.SuspendingOperation.IsComplete);
        }

        [Test]
        public void TestAppService_OnAppSuspending_ShouldDisconnect()
        {
            // Arrange 
            var appService = new AppService();
            var suspendingEventArgs = new SuspendingEventArgs();

            // Act 
            appService.OnAppSuspending(this, suspendingEventArgs);

            // Assert
            Assert.IsFalse(appService.IsConnected);
        }
    }
}
