// Test generated by RoostGPT for test Csharp-dev-toys using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using NUnit.Framework;
using System;
using System.Composition;
using DevToys.Api.Core;

namespace DevToys.Core
{
    [TestFixture]
    public class NotificationServiceTests
    {
        [Test]
        public void TestNotificationService_ShowInAppNotification_Success()
        {
            // Arrange
            NotificationService notificationService = new NotificationService();
            string title = "Test Title";
            string message = "Test Message";

            // Act
            notificationService.ShowInAppNotification(title, message);

            // Assert
            Assert.NotNull(notificationService.InAppNotificationAdded);
            Assert.AreEqual(title, notificationService.InAppNotificationAddedEventArgs.Title);
            Assert.AreEqual(message, notificationService.InAppNotificationAddedEventArgs.Message);
        }

        [Test]
        public void TestNotificationService_ShowInAppNotification_NullTitle()
        {
            // Arrange
            NotificationService notificationService = new NotificationService();
            string title = null;
            string message = "Test Message";

            // Act & Assert
            Assert.Throws<ArgumentNullException>(() => notificationService.ShowInAppNotification(title, message));
        }
    }
}
