// Test generated by RoostGPT for test Csharp-dev-toys using AI Type Open AI and AI Model gpt-3.5-turbo-0301

using NUnit.Framework;
using System.Threading;

namespace DevToys.Core
{
    [TestFixture]
    public class TestClass
    {
        private SemaphoreSlim _semaphore;

        [SetUp]
        public void SetUp()
        {
            _semaphore = new SemaphoreSlim(1, 1);
        }

        [Test]
        public void TestMarketingService_Dispose_8e158f5715()
        {
            // Arrange

            // Act
            _semaphore.Dispose();

            // Assert
            Assert.That(() => _semaphore.Release(), Throws.TypeOf<SemaphoreFullException>());
        }

        [Test]
        public void TestMarketingService_Dispose_9f3a1d6b57()
        {
            // Arrange
            var semaphore = new SemaphoreSlim(1, 1);

            // Act
            semaphore.Dispose();

            // Assert
            Assert.That(() => semaphore.Release(), Throws.TypeOf<SemaphoreFullException>());
        }
    }
}
